### ISSUE TITLE
Listen on interface

### ISSUE THREAD

**Issue by mhsjlw** [phoboslab/jsmpeg-vnc#45]
Is there a way to bind to a certain IP/interface? I'm trying to use this on Microsoft Azure but it isn't letting me connect from outside. I've also tried using ZeroTier but it doesn't seem to route through that either. Any ideas?

**Comment by kishorv06** [comment]
Make sure the IP you are connecting to is accessible. Try a ping test. If it is accessible then check if the ports are open or closed. I don't think Microsoft would expose their cloud computers directly to the internet. They should be having some kind of filtering on the traffic or the ports. Make sure that the IP shown in ifconfig and Whatismyip.org is the same. Otherwise, you are behind a router that prevents others from accessing the PC over internet.

**Comment by mhsjlw** [comment]
They do not. The problem is listening on an interface because I am using a VPN to connect to the server so I don't need to open ports in the firewall. The problem is that I can't get it to run on the VPN interface, it tries to run on something else

**Comment by kishorv06** [comment]
This function determines the IP to bind to. May be you could modify it to make it work over VPN. Make sure you are using a VPN that supports port forwarding.

https://github.com/phoboslab/jsmpeg-vnc/blob/master/source/server.c#L79

**Comment by mhsjlw** [comment]
Perfect, I'll give it a try
